Update Developer guide for bookmark feature
AY2021S1-CS2113T-T12-1/tp pull request #102
Opened 2020-10-22 17:51 UTC by lingsihui

Fixes #101

2020-10-22 18:09 UTC, farice9 requested changes

2020-10-22 18:09 UTC, farice9 commented on docs/DeveloperGuide.md
> +Given below, figure 2, is the sequence diagram of how the classes interact with each
I think need to Figure 2 instead of figure 2

2020-10-22 18:09 UTC, farice9 commented on docs/DeveloperGuide.md
> +As shown in figure 2, when `BookmarkRun` is called,
Same thing here

2020-10-22 18:09 UTC, farice9 commented on docs/DeveloperGuide.md
>  {Describe the design and implementation of the product. Use UML diagrams and short code snippets where applicable.}
Are we keeping this line?

2020-10-22 18:09 UTC, farice9 commented on docs/DeveloperGuide.md
Everything else looks goood

2020-10-23 09:15 UTC, farice9 approved these changes

2020-10-23 09:31 UTC, farice9 commented
Sorry wrongly approved, wait for new push before merging

2020-10-23 11:00 UTC, slightlyharp commented
LGTM

2020-10-23 11:00 UTC, merged